steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '-t' 
  - 'gcr.io/$PROJECT_ID/nodejs-service:main_$SHORT_SHA' 
  - '--build-arg' 
  - 'COMMIT_SHA=$COMMIT_SHA' 
  - '-f' 
  - 'Dockerfile' 
  - '.'
images: ['gcr.io/$PROJECT_ID/nodejs-service:main_$SHORT_SHA']
