# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  
  build:
    # Use `docker:stable` as the Docker container to run this job in
    docker:
      - image: cimg/base:stable

    steps:
      # Checkout the repository files
      - checkout

      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker:
          version: 20.10.24

      # Build the hello world image
      - run:
          name: Build Docker image
          command: docker build -t nodejs-service:latest .
      
      # Install Docker Scout          
      - run:
          name: Scan image for CVEs
          command: |
            mkdir -p $DOCKER_HOME/cli-plugins
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            ./docker-scout cves nodejs-service:latest --exit-code --only-severity critical,high

workflows:
  say-hello-workflow:
    jobs:
      - build
